name: pol

on:
  push:

env:
  BACK_EXEC: "pol-back"

jobs:
  pol-back-build:
    runs-on: ubuntu-latest
    container:
      image: golang:1.22.2
    steps:
      - uses: actions/checkout@v3
      - name: build project
        run: |
          cd backend
          go mod download
          go buid main.go -o $BACK_EXEC
          if [[ ! -f $BACK_EXEC ]]; then
            echo "::error title=This executable was not found $BACK_EXEC::"
            exit 1
          fi
