name: pol

on:
  push:
    branches:
      - master
      - fix/ci

env:
  BACK_EXEC: "pol-back"

jobs:
  pol-back-build:
    runs-on: ubuntu-22.04
    container:
      image: golang:1.22.5
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 1.22.5
      - name: build project
        run: |
          go get .
          go build -o $BACK_EXEC -buildvcs=false
          if [[ ! -f $BACK_EXEC ]]; then
            echo "::error title=This executable was not found $BACK_EXEC::"
            exit 1
          fi
  pol-front:
    needs: pol-back-build
    runs-on: ubuntu-22.04
    container:
      image: node:21.6.2
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 21.6.2
      - uses: cypress-io/github-action@v6
      - name: build project front
        working-directory: frontend
        run: |
          yarn install
          yarn build
          yarn cy:run
