name: pol

on:
  push:

env:
  BACK_EXEC: "pol-back"

jobs:
  pol-back-build:
    runs-on: ubuntu-22.04
    container:
      image: golang:1.22.5
    steps:
      - uses: actions/setup-go@v5
      - name: build project
        run: |
          cd backend
          go mod download
          go build -o $BACK_EXEC
          if [[ ! -f $BACK_EXEC ]]; then
            echo "::error title=This executable was not found $BACK_EXEC::"
            exit 1
          fi
  pol-front-build:
    needs: pol-back-build
    runs-on: ubuntu-22.04
    container:
      image: oven/bun:1
    steps:
      - uses: actions/checkout@v3
      - name: build project front
        run: |
          cd frontend
          bun install
          bun run build
  pol-front-cypress-tests:
    needs: pol-front-
    runs-on: ubuntu-22.04
    container:
      image: oven/bun:1
    steps:
      - uses: cypress-io/github-action@v6
      - name: test project front using cypress
        run: |
          cd frontend
          bun install
          bun run cy:run
