name: pol

on:
  push:

env:
  BACK_EXEC: "pol-back"

jobs:
  pol-back-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ '1.19', '1.20', '1.21.x' ]
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      - name: Build Pol backend
        run: |
          cd backend
          go mod download
          go build -o $BACK_EXEC
          if [[ ! -f $BACK_EXEC ]]; then
            echo "::error title=This executable was not found $BACK_EXEC::"
            exit 1
          fi
  pol-front-build:
    runs-on: ubuntu-latest
    container:
      image: oven/bun:1
    steps:
      - uses: actions/checkout@v3
      - name: build project front
        run: |
          cd frontend
          bun install
          bun run build
  pol-front-cypress-tests:
    needs: pol-front-build
    runs-on: ubuntu-latest
    container:
      image: oven/bun:1
    steps:
      - uses: actions/checkout@v3
      - name: test project front using cypress
        run: |
          cd frontend
          bun install
          bun run cy:run
